version: '3.9'

services:
  db:
    image: postgres:13.7
    restart: unless-stopped
    environment:
      POSTGRES_DB: kari
      POSTGRES_USER: kari
      POSTGRES_PASSWORD: kari
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./local-kari-db:/var/lib/postgresql/data

volumes:
  local-kari-db:
